mobile_phones = [
    {'name': "iPhone 14", 'category': 'Mobile Phone, smartphone'},
    {'name': "iPhone 15", 'category': 'Mobile Phone, smartphone'},
    {'name': "iPhone 16", 'category': 'Mobile Phone, smartphone'},
    {'name': "Samsung Galaxy S23", 'category': 'Mobile Phone, smartphone'},
    {'name': "Samsung Galaxy S24", 'category': 'Mobile Phone, smartphone'},
    {'name': "Motorola Edge 50 pro", 'category': 'Mobile Phone, smartphone'},
    {'name': "Sony Xperia 1 V", 'category': 'Mobile Phone, smartphone'},
    {'name': "Sony Xperia 2", 'category': 'Mobile Phone, smartphone'},
    {'name': "MI 12", 'category': 'Mobile Phone, smartphone'},
    {'name': "MI 13", 'category': 'Mobile Phone, smartphone'},
    {'name': "Xiaomi Mi 12", 'category': 'Mobile Phone, smartphone'},
    {'name': "Xiaomi Mi 13", 'category': 'Mobile Phone, smartphone'},
    {'name': "Sony Xperia 5 IV", 'category': 'Mobile Phone, smartphone'},
    {'name': "Sony Xperia 1 V", 'category': 'Mobile Phone, smartphone'},
    {'name': "Oppo Find X6", 'category': 'Mobile Phone, smartphone'},
    {'name': "Oppo Reno8", 'category': 'Mobile Phone, smartphone'},
    {'name': "Realme GT 3", 'category': 'Mobile Phone, smartphone'},
    {'name': "Vivo X90", 'category': 'Mobile Phone, smartphone'},
    {'name': "Samsung Galaxy Note 22", 'category': 'Mobile Phone, smartphone'},
    {'name': "Huawei P60", 'category': 'Mobile Phone, smartphone'},
    {'name': "Nokia G50", 'category': 'Mobile Phone, smartphone'},
    {'name': "Asus Zenfone 9", 'category': 'Mobile Phone, smartphone'},
    {'name': "Pigeon Blender", 'category': 'Kitchen Accessories, Blender'},
    {'name': "AGARO Marvel 9L Oven", 'category': 'Kitchen Accessories, Oven'},
    {'name': "Pigeon Electric Kettle", 'category': 'Kitchen Accessories, Kettle'},
    {'name': "SOFLIN Egg Boiler Electric", 'category': 'Kitchen Accessories, Egg Boiler'},
    {'name': "NutriPro Juicer Mixer Grinder", 'category': 'Kitchen Accessories, Mixer'},
    {'name': "Butterfly Smart 2 Litres Table-Top Wet Grinder", 'category': 'Kitchen Accessories, Grinder'},
    {'name': "Pigeon by Stovekraft Cruise 1800 watt", 'category': 'Kitchen Accessories, StoveKraft'},
    {'name': "KENT 16051 Hand Blender 300 W", 'category': 'Kitchen Accessories, Hand Blender'},
    {'name': "Pigeon Healthifry Digital Air Fryer", 'category': 'Kitchen Accessories, Air Fryer'},
    {'name': "Lipstick", 'category': 'Cosmetic, Beauty, Makeup'},
    {'name': "Foundation", 'category': 'Cosmetic, Beauty, Makeup'},
    {'name': "compact powder", 'category': 'Cosmetic, Beauty, Makeup'},
    {'name': "Blush", 'category': 'Cosmetic, Beauty, Makeup'},
    {'name': "Long lasting Eyeliner", 'category': 'Cosmetic, Beauty, Makeup'},
    {'name': " waterproof Eyeliner", 'category': 'Cosmetic, Beauty, Makeup'},
    {'name': "Gel Eyeliner", 'category': 'Cosmetic, Beauty, Makeup'},
    {'name': "Pen Eyeliner", 'category': 'Cosmetic, Beauty, Makeup'},
    {'name': "Liquid Eyeliner", 'category': 'Cosmetic, Beauty, Makeup'}
]

appliance_models = [
    "Samsung Refrigerator RT34", "LG Washing Machine FH2", "Whirlpool Microwave Oven MW20",
    "Dyson V11 Vacuum Cleaner", "Philips Air Fryer HD9650", "Sony Bravia 4K TV X90J",
    "Panasonic AC CS/CU-NU18", "Bosch Dishwasher SMS46", "IFB Oven 30SC3",
    "Bajaj Mixer Grinder GX8", "Haier Deep Freezer HDF335", "Prestige Induction Cooktop PIC 20",
    "Morphy Richards Toaster AT 201", "Usha Ceiling Fan Striker", "Havells Water Heater Monza",
    "Samsung Refrigerator RT34", "LG Washing Machine FH2",    "Whirlpool Microwave Oven MW20",
    "Dyson Vacuum Cleaner V11", "Bosch Dishwasher Series 4", "Philips Air Fryer HD9650",
    "Panasonic Air Conditioner CS-CU-YU18WKYTM", "Breville Espresso Machine BES870",
    "Sony Home Theater System HT-S20R", "GE Electric Range JB645RKSS", "Frigidaire Freezer FFUE2022AW",
    "Sharp Air Purifier FP-F30UH",   "Toshiba Heat Pump HWS-802XWHM3",   "LG OLED TV 55 inch",
    "Kenmore Elite Dryer 61633",   "Hamilton Beach Slow Cooker 33969A",
    "Black + Decker Toaster Oven TO3250XSB",   "KitchenAid Stand Mixer KSM150PSER",   "Ninja Blender BL610",
    "Honeywell Thermostat RTH9585WF",   "Samsung Gas Range NX58H5600SS",   "Danby Mini Fridge DAR044A4BDD-3",
    "Eureka Upright Vacuum AS3401AX",   "Braun Coffee Maker KF7170SI",   "Instant Pot Pressure Cooker DUO60"
]


