import asyncio
import logging
import uuid
from typing import Literal, Any, List, Optional
import os
import yaml

from superagentx.agent import Agent
from superagentx.agentxdag import InMemoryStore, AgentXDag, WorkflowBlueprint
from superagentx.config import is_verbose_enabled
from superagentx.router.router_engine import RouterEngine
from superagentx.constants import SEQUENCE, PARALLEL
from superagentx.exceptions import StopSuperAgentX
from superagentx.result import GoalResult
from superagentx.db_store import ConfigLoader
from superagentx.utils.helper import iter_to_aiter, StatusCallback, _maybe_await
from superagentx.utils.observability.trace_decorator import pipe_trace


is_verbose_enabled()

logger = logging.getLogger(__name__)


class AgentXPipe:

    def __init__(
            self,
            *,
            pipe_id: str | None = None,
            name: str | None = None,
            description: str | None = None,
            agents: list[Agent | list[Agent]] | None = None,
            router: RouterEngine | None = None,
            memory: Any | None = None,
            stop_if_goal_not_satisfied: bool = False,
            workflow_store: bool = False,
            stop_on_node_failure: bool = True,
            platform_url: Optional[str] = None
    ):
        """
        Initializes a new instance of the class with specified parameters.

        This constructor sets up an object that can manage a collection of agents,
        define a goal and role, and utilize a prompt for processing. Each instance
        can be uniquely identified by the `pipe_id`, which defaults to a newly
        generated UUID if not provided. This structure is particularly useful for
        organizing and executing workflows that involve multiple agents working
        toward a common goal.

        Args:
            pipe_id: A unique identifier for the agentxpipe. If not provided, a new UUID
                will be generated by default. Useful for tracking or referencing
                the agentxpipe in multi-engine environments.
            name: An optional name for the agentxpipe, providing a more friendly reference for display or
                logging purposes.
            description: An optional description that provides additional context or details about the agentxpipe's
                purpose and capabilities.
            agents: A list of Agent instances (or lists of Agent instances) that are part of this structure.
                These agents can perform tasks and contribute to achieving the defined goal.
            memory: An optional memory instance that allows the engine to retain information across interactions.
                This can enhance the pipe's contextual awareness and improve its performance over time.
            workflow_store: A flag to indicate agentic workflow is required to persist states. This is useful, if a human
                    approvals are enabled to wait and act after a human action is being performed.
            stop_if_goal_not_satisfied: A flag indicating whether to stop processing if the goal is not satisfied.
                When set to True, the agentxpipe operation will halt if the defined goal is not met,
                preventing any further actions. Defaults to False, allowing the process to continue regardless
                of goal satisfaction.
        """
        self.pipe_id = pipe_id or uuid.uuid4().hex
        self.name = name or f'{self.__str__()}-{self.pipe_id}'
        self.description = description
        self.agents: list[Agent | list[Agent]] = agents or []
        self.router = router
        self.memory = memory
        if self.memory:
            self.memory_id = uuid.uuid4().hex
        self.workflow_store = workflow_store
        self.storage = None
        self.stop_if_goal_not_satisfied = stop_if_goal_not_satisfied
        self.stop_on_node_failure = stop_on_node_failure
        self.platform_url = platform_url or os.getenv("PLATFORM_URL")


        logger.debug(
            f'Initiating AgentXPipe...\n'
            f'Id : {self.pipe_id}\n'
            f'Name : {self.name}\n'
            f'Description : {self.description}\n'
            f'Agents Associated : {",".join([str(_agent) for _agent in self.agents])}\n'
            f'Memory Configured : {self.memory}\n'
            f'Stop if goal not satisfied configured : {self.stop_if_goal_not_satisfied}\n'
        )

    def __str__(self):
        return "AgentXPipe"

    def __repr__(self):
        return f"<{self.__str__()}>"

    async def add(
            self,
            *agents: Agent,
            execute_type: Literal['SEQUENCE', 'PARALLEL'] = 'SEQUENCE'
    ) -> None:
        """
        Adds one or more Agent instances to the current context for processing.

        This method allows the user to include multiple agents that will be used
        for execution based on the specified execution type. The `execute_type`
        parameter determines how the engines will be run: either in a sequence,
        where each engine runs one after the other, or in parallel, where all
        specified agents run concurrently.

        Args:
            agents: One or more Agent instances to be added to the context.
                This allows for flexibility in processing and task execution based on different capabilities
                or configurations.
            execute_type: The method of execution for the added engines.
                - 'SEQUENCE': Agents are executed one after another,
                  waiting for each to complete before starting the next.
                - 'PARALLEL': All agents are executed concurrently, allowing for
                  simultaneous processing.
                Default is 'SEQUENCE'.

        Returns:
            None
        """
        if execute_type == SEQUENCE:
            self.agents += agents
            logger.debug(f'Agent(s) added as {SEQUENCE} : {",".join([str(_agent) for _agent in agents])}')
        else:
            self.agents.append(list(agents))
            logger.debug(f'Agents added as {PARALLEL} : {",".join([str(_agent) for _agent in agents])}')

    @staticmethod
    async def _pre_result(
            results: list[GoalResult] | None = None
    ) -> list[str]:
        if not results:
            return []
        return [
            (f'Reason: {result.reason}\n'
             f'Result: \n{yaml.dump(result.result)}\n'
             f'Content: \n{result.content}'
             f'Is Goal Satisfied: {result.is_goal_satisfied}\n\n')

            async for result in iter_to_aiter(results)
        ]

    async def add_memory(
            self,
            prompt_instruction: list[dict],
            conversation_id: str | None = None
    ) -> None:
        """
        Adds a list of prompt instructions to the memory of the engine.

        This method is designed to enhance the engine's contextual awareness by storing
        relevant prompt instructions in its memory. The stored instructions can be
        referenced in future interactions, allowing the engine to recall important
        information and improve its responses over time.

        Args:
            prompt_instruction: A list of dictionaries containing prompt instructions to be added to the engine's memory.
                Each dictionary should contain structured data relevant to the prompts, which may include keys such as
                'text', 'context', or any other relevant attributes that define the prompt instructions.
            conversation_id: A string representing the unique identifier of the conversation.

        Returns:
            None
        """
        logger.debug(f'Add prompt instruction to the memory : {prompt_instruction}')
        async for prompt in iter_to_aiter(prompt_instruction):
            await self.memory.add(
                memory_id=self.memory_id,
                conversation_id=conversation_id,
                message_id=uuid.uuid4().hex,
                role=prompt.get("role"),
                data=prompt.get("content"),
                reason=prompt.get("reason")
            )

    async def retrieve_memory(
            self,
            query_instruction: str,
            conversation_id: str | None = None
    ) -> list[dict]:
        """
        Retrieves a list of prompt instructions from the engine's memory based on the provided query instruction.

        This method allows the engine to search its memory for stored prompt instructions
        that match or are relevant to the given query. The retrieved instructions can be
        used to inform responses, provide context, or assist in decision-making during
        future interactions.

        Args:
            query_instruction: A string representing the query used to search the engine's memory.
                This instruction should be formulated in a way that allows the engine to identify relevant stored
                prompts.
            conversation_id: A string representing the unique identifier of the conversation.

        Returns:
            list[dict]
                A list of dictionaries containing the retrieved prompt instructions that match the query.
                Each dictionary represents an instruction and may contain keys such as 'text', 'context',
                and other relevant attributes that describe the prompt.
        """
        logger.debug(f'Retrieving memory by query : {query_instruction}')
        return await self.memory.search(
            query=query_instruction,
            memory_id=self.memory_id,
            limit=10,
            conversation_id=conversation_id
        )

    async def _flow(
            self,
            query_instruction: str,
            verify_goal: bool = True,
            conversation_id: str | None = None,
            status_callback: StatusCallback | None = None
    ):
        trigger_break = False
        results: list[GoalResult] = []
        previous_agent_result: str | None = None,
        old_memory = None

        # ----------------------------
        # Setup Storage (once)
        # ----------------------------
        if self.workflow_store:
            self.storage = await ConfigLoader.load_db_config()
            await self.storage.setup()

            await self.storage.create_pipe(
                pipe_id=self.pipe_id,
                conversation_id=conversation_id,
                input_query=query_instruction,
                executed_by="Agent_System"
            )

            await self.storage.update_pipe_status(
                pipe_id=self.pipe_id,
                status="In-Progress"
            )

        try:
            async for _agents in iter_to_aiter(self.agents):

                pre_result = await self._pre_result(results=results)

                if self.memory:
                    old_memory = await self.retrieve_memory(
                        query_instruction,
                        conversation_id=conversation_id
                    )

                # ----------------------------
                # EXECUTION BLOCK
                # ----------------------------
                try:

                    # ==========================
                    # PARALLEL EXECUTION
                    # ==========================
                    if isinstance(_agents, list):

                        agents_list = [
                            agent async for agent in iter_to_aiter(_agents)
                        ]

                        # ----------------------------------
                        # ROUTER INVOCATION
                        # ----------------------------------
                        if self.router:
                            try:
                                context = {
                                    "query": query_instruction,
                                    "pre_result": pre_result,
                                    "conversation_id": conversation_id
                                }
                                routed_agents = await self.router.route(
                                    agents_list,
                                    context
                                )
                                if routed_agents:
                                    agents_list = routed_agents

                                logger.debug(
                                    f"Router selected agents: "
                                    f"{','.join([a.role for a in agents_list])}"
                                )
                            except Exception as e:
                                logger.warning(f"Router failed: {e}")

                        logger.debug(
                            f'Executing Parallel Agents: '
                            f'{",".join([str(a) for a in agents_list])}'
                        )

                        parallel_results = await asyncio.gather(
                            *[
                                agent.execute(
                                    query_instruction=query_instruction,
                                    pipe_id=self.pipe_id,
                                    pre_result=pre_result,
                                    previous_agent_result=previous_agent_result,
                                    old_memory=old_memory,
                                    verify_goal=verify_goal,
                                    stop_if_goal_not_satisfied=self.stop_if_goal_not_satisfied,
                                    conversation_id=conversation_id,
                                    storage=self.storage,
                                    status_callback=status_callback
                                )
                                for agent in agents_list
                            ],
                            return_exceptions=True  #prevents crash
                        )
                        # Normalize and handle failures individually
                        for agent, res in zip(agents_list, parallel_results):

                            if isinstance(res, Exception):
                                logger.error(
                                    f"Agent {agent.name} failed: {res}",
                                    exc_info=True
                                )
                                continue  # Don't break entire pipe

                            if not res:
                                continue

                            results.append(res)
                            if getattr(res, "result", None):
                                previous_agent_result += (res.result,)

                            # Memory write
                            if (
                                    self.memory
                                    and getattr(res, "result", None)
                                    and getattr(res, "reason", None)
                            ):
                                assistant = {
                                    "role": "assistant",
                                    "content": f"{yaml.dump(res.result)}",
                                    "reason": res.reason
                                }
                                await self.add_memory(
                                    [assistant],
                                    conversation_id=conversation_id
                                )

                    # ==========================
                    # SEQUENTIAL EXECUTION
                    # ==========================
                    else:

                        agent = _agents

                        logger.debug(f'Executing Agent: {agent}')

                        res = await agent.execute(
                            query_instruction=query_instruction,
                            pipe_id=self.pipe_id,
                            pre_result=pre_result,
                            previous_agent_result=previous_agent_result,
                            old_memory=old_memory,
                            verify_goal=verify_goal,
                            stop_if_goal_not_satisfied=self.stop_if_goal_not_satisfied,
                            conversation_id=conversation_id,
                            storage=self.storage,
                            status_callback=status_callback
                        )
                        if res:
                            results.append(res)

                            if getattr(res, "result", None):
                                previous_agent_result = res.result

                            if (
                                    self.memory
                                    and getattr(res, "result", None)
                                    and getattr(res, "reason", None)
                            ):
                                assistant = {
                                    "role": "assistant",
                                    "content": f"{yaml.dump(res.result)}",
                                    "reason": res.reason
                                }
                                await self.add_memory(
                                    [assistant],
                                    conversation_id=conversation_id
                                )

                except StopSuperAgentX as ex:
                    trigger_break = True
                    logger.warning(ex)

                    if ex.goal_result:
                        results.append(ex.goal_result)

                    break  # intentional stop

                except PermissionError as ex:
                    logger.warning("Policy denied execution: %s", ex)

                    results.append(
                        GoalResult(
                            name=agent.name,
                            agent_id=agent.agent_id,
                            result="Request denied by governance policy.",
                            reason=str(ex),
                            error=str(ex),
                            verify_goal=False,
                            is_goal_satisfied=False,
                        )
                    )

                    return results

                except Exception as ex:
                    # Do NOT crash the pipe
                    logger.error(
                        f"Unexpected error in agent execution: {ex}",
                        exc_info=True
                    )
                    continue

                if trigger_break:
                    break

            return results

        finally:
            # ----------------------------
            # Close Storage Safely
            # ----------------------------
            if self.workflow_store and self.storage:
                try:
                    await self.storage.update_pipe_status(
                        self.pipe_id,
                        "Completed" if not trigger_break else "Failed"
                    )
                    await self.storage.close()
                    logger.info(f"DB connection closed for pipe {self.pipe_id}")
                except Exception as e:
                    logger.warning(f"Failed to close DB connection: {e}")


    async def flow(
            self,
            *,
            query_instruction: str = None,
            pre_result: list | None = None,
            run_id: str | None = None,
            verify_goal: bool = False,
            conversation_id: str | None = None,
            status_callback: StatusCallback | None = None
    ):
        """
        Executes the AgentXPipe workflow.

        Example
        -------
        pipe = AgentXPipe(
            agents=[
                [agent_seo, agent_linkedin, agent_twitter],
                summary_agent
            ]
        )

        await pipe.flow(
            query_instruction="Write LinkedIn content"
        )
        """

        if not self.agents:
            raise ValueError("No agents configured for AgentXPipe.")

        run_id = run_id or str(uuid.uuid4())

        # -----------------------------------------------------
        # Normalize into execution layers
        #
        # Example:
        # [
        #     agent1,
        #     [agent2, agent3],
        #     agent4
        # ]
        #
        # becomes
        #
        # [
        #     [agent1],
        #     [agent2, agent3],
        #     [agent4]
        # ]
        # -----------------------------------------------------

        layers: list[list[Agent]] = []

        for layer in self.agents:
            if isinstance(layer, list):
                if not layer:
                    continue
                layers.append(layer)
            else:
                layers.append([layer])

        blueprint = WorkflowBlueprint(
            name=self.name or "AgentX Workflow"
        )

        # -----------------------------------------------------
        # Register Nodes
        # -----------------------------------------------------

        registered: set[str] = set()

        for layer in layers:
            for agent in layer:

                if agent.name in registered:
                    continue

                blueprint.add_node(agent)
                registered.add(agent.name)

        # -----------------------------------------------------
        # Build Dependencies
        # -----------------------------------------------------

        for current_layer, next_layer in zip(layers, layers[1:]):
            source = (
                current_layer[0].name
                if len(current_layer) == 1
                else [agent.name for agent in current_layer]
            )

            destination = (
                next_layer[0].name
                if len(next_layer) == 1
                else [agent.name for agent in next_layer]
            )
            blueprint.add_path(source, destination)

        if status_callback:
            await _maybe_await(status_callback(
                event="pipe_flow_start",
                pipe_id=self.pipe_id,
                query=query_instruction,
                conversation_id=conversation_id
            ))

        # -----------------------------------------------------
        # Create Store
        # -----------------------------------------------------

        store = InMemoryStore()

        # -----------------------------------------------------
        # Create DAG Engine
        # -----------------------------------------------------

        dag_engine = AgentXDag(
            blueprint=blueprint,
            store=store,
            pipe_id=self.pipe_id,
            name=self.name,
            description=self.description,
            router=self.router,
            memory=self.memory,
            workflow_store=self.workflow_store,
            stop_if_goal_not_satisfied=self.stop_if_goal_not_satisfied,
            stop_on_node_failure=self.stop_on_node_failure,
        )

        # -----------------------------------------------------
        # Execute Workflow
        # -----------------------------------------------------

        await dag_engine.execute(
            run_id=run_id,
            verify_goal=verify_goal,
            conversation_id=conversation_id,
            initial_ctx={
                "query_instruction": query_instruction,
                "pre_result": pre_result or [],
            },
            status_callback=status_callback,
        )

        # -----------------------------------------------------
        # Return Checkpoint
        # -----------------------------------------------------

        checkpoint = store.load(run_id)

        goal_result: list[GoalResult] = []
        if checkpoint:
            goal_result = checkpoint.goal_results

        if status_callback:
            await _maybe_await(status_callback(
                event="pipe_flow_end",
                pipe_id=self.pipe_id,
                query=query_instruction,
                conversation_id=conversation_id,
                result=goal_result
           ))

        return checkpoint, goal_result

    async def _load_storage_once(self):
        """
        Lazily initialize storage exactly once per pipe.
        Used by observability decorators.
        """
        if self.storage:
            return self.storage

        from superagentx.db_store import ConfigLoader

        self.storage = await ConfigLoader.load_db_config()
        await self.storage.setup()
        return self.storage